### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by LUFCMOT** [ilendemli/gumer-psn-php#16]
Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 52: Empty reply from server [url] https://auth.api.sonyentertainmentnetwork.com/2.0/oauth/authorize?response_type=code&service_entity=urn%3Aservice-entity%3Apsn&returnAuthCode=true&cltm=1399637146935&redirect_uri=com.scee.psxandroid.scecompcall%3A%2F%2Fredirect&client_id=b0d0d7ad-bb99-4ab1-b25e-afa0c76577b0&scope=psn%3Asceapp' in /home/utcoin/public_html/files/classes/gumer-psn-php-master/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:338 Stack trace: #0 /home/utcoin/public_html/files/classes/gumer-psn-php-master/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array) #1 /home/utcoin/public_html/files/classes/gumer-psn-php-master/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\C in /home/utcoin/public_html/files/classes/gumer-psn-php-master/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 338

I just get this - anyone getting the same or?

**Comment by xXREDXIIIIXx** [comment]
My website is fully functional based on this code. You have done something wrong. (I am using a previous version of this code - but I know this version works too)

**Comment by noxify** [comment]
I think the problem is here, that sometimes the oauth service is not available.
Currently I have the same problem, but if I try it to login via browser, I get an Error with "ERR_EMPTY_RESPONSE".

Tested in Google Chrome with OSX.

**Comment by kevinliteon** [comment]
it seems that the server blocks IP addresses after a moment... I had the same problem as you and after changing my IP address, the server replied
